# Generated by Django 6.1.1 on 2026-09-28 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('required_level', models.IntegerField(default=1)),
                ('sprite_asset_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='current_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_cards_memorized',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='equipped_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_by', to='profiles.title'),
        ),
        migrations.AddField(
            model_name='profile',
            name='unlocked_titles',
            field=models.ManyToManyField(blank=True, related_name='unlocked_by', to='profiles.title'),
        ),
    ]
